void autorecover1(int x,int y)
{
	int posx1=0,posy1=0;
	int posx2=0,posy2=0;
	for(int i=0;i<M;i++)
	   {
	   	for(int j=0;j<N;j++)
	   	   {
	   	   	if(now[i][j]==begin[y][x]+1)
	   	   	  {
	   	   	  	posy2=i;
	   	   	  	posx2=j;
	   	   	  	break;
	   	   	  }
	   	   }
	   }
	for(int i=0;i<M;i++)
	   {
	   	for(int j=0;j<N;j++)
	   	   {
	   	   	if(now[i][j]==begin[y][x])
	   	   	  {
	   	   	  	posy1=i;
	   	   	  	posx1=j;
	   	   	  	break;
	   	   	  }
	   	   }
	   }
	if(posx1==x && posy1==y && posx2==x+1 && posy2==y)
	  {
	  	return;
	  }
	if(posy2==y)//posy2==y
	  {
	  	if(posx2==x+1)
	  	{
	  	if(ly==y)
	  	{
	  		if(lx<posx2)
	  	      {
	  	      	D();
	  	      	posx2--;
	  	      }
	  	}
	  	else//ly>y
	  	{
	  		if(lx==posx2)
	  		  {
	  		  	A();
	  		  	for(int i=ly;i>y;i--)
	  		  	   {
	  		  	   	W();
	  		  	   }
	  		  	D();
	  		  	posx2--;
	  		  }
	  		else
	  		  {
	  		  	if(lx<posx2)
	  		  	{
	  		  		for(int i=lx;i<posx2-1;i++)
	  		  	      {
	  		  	   		D();
	  		  	      }
	  		  		for(int i=ly;i>y;i--)
	  		  	      {
	  		  	   	    W();
	  		  	      }
	  		  	    D();
	  		  	    posx2--;
	  		  	}	            
	  		  }
	  	} 
	   }
	  }//posy2==y
	else//posy2!=y
	  {
	  	if(posx2==x)
	  	  {
	  	  	if(ly<posy2)
	  	  	  {
	  	  	  	for(int i=ly;i<posy2-1;i++)
	  	  	  	   {
	  	  	  	   	S();
	  	  	  	   }
	  	  	  }
	  	  	else
	  	  	  {
	  	  	  	if(ly==posy2)
	  	  	  	  {
	  	  	  	  	if(ly==M-1)
	  	  	  	  	  {
	  	  	  	  	  	W();
	  	  	  	  	  }
	  	  	  	  	else
	  	  	  	  	  {
	  	  	  	  	  	S();
	  	  	  	  	  }
	  	  	  	  }
	  	  	  	else
	  	  	  	  {
	  	  	  	  	for(int i=ly;i>posy2+1;i--)
	  	  	  	  	   {
	  	  	  	  	   	W();
	  	  	  	  	   }
	  	  	  	  }	  	  	  		  	  	  	
	  	  	  }
	  	  	if(lx>posx2)
	  	  	  	  {
	  	  	  	  	for(int i=lx;i>posx2;i--)
	  	  	  	  	   {
	  	  	  	  	   	A();
	  	  	  	  	   }
	  	  	  	  }
	  	  	else
	  	  	  	  {
	  	  	  	  	for(int i=lx;i<posx2;i++)
	  	  	  	  	   {
	  	  	  	  	   	D();
	  	  	  	  	   }
	  	  	  	  }
	  	  	if(ly<posy2)
	  	  	  {
	  	  	  	S();
	  	  	  	posy2--;
	  	  	 while(posy2>y)
	  	  	  	{
	  	  	  	    D();
	  	  	  	    W();
	  	  	  	    W();
	  	  	  	    A();
	  	  	  	    S();
	  	  	  	    posy2--;
	  	  	    }
	  	      }
	  	    else
	  	      {
	  	      	while(posy2>y)
	  	  	  	{
	  	  	  	    D();
	  	  	  	    W();
	  	  	  	    W();
	  	  	  	    A();
	  	  	  	    S();
	  	  	  	    posy2--;
	  	  	    }
	  	      }
	  	  }
	  	else//posx2!=x,posy2!=y
	  	  {
	  	  	if(posx2<x)
	  	  	{
	  	  	 if(ly!=posy2) 
	  	  	  {
	  	  	  	if(ly<posy2)
	  	  	  	  {
	  	  	  	   for(int i=ly;i<posy2-1;i++)
	  	  	  	      {
	  	  	  	     	S();
	  	  	  	      }
	  	  	      }
	  	  	    else
	  	  	      {
	  	  	      	for(int i=ly;i>posy2+1;i--)
	  	  	      	   {
	  	  	      	   	W();
	  	  	      	   }
	  	  	      }
	  	  	  }
	  	  	 else//ly==posy2
	  	  	  {
	  	  	  	if(posy2==M-1)
	  	  	  	  {
	  	  	  	  	W();
	  	  	  	  }
	  	  	  	else
	  	  	  	  {
	  	  	  	  	S();
	  	  	  	  }
	  	  	  }
	  	  	 if(lx<=posx2)
	  	  	  {
	  	  	  	for(int i=lx;i<posx2;i++)
	  	  	  	   {
	  	  	  	   	D();
	  	  	  	   }
	  	  	  	if(ly>posy2)
	  	  	  	  {
	  	  	  	  	D();
	  	  	  	  	W();
	  	  	  	  	A();
	  	  	  	  	posx2++;
	  	  	  	  	while(posx2<x)
	  	  	  	  	     {
	  	  	  	  	     	S();
	  	  	  	  	     	D();
	  	  	  	  	     	D();
	  	  	  	  	     	W();
	  	  	  	  	     	A();
	  	  	  	  	     	posx2++;
	  	  	  	  	     }
	  	  	  	  	S();
	  	  	  	  	D();
	  	  	  	  	while(posy2>y)
	  	  	  	  	     {
	  	  	  	  	     	D();
	  	  	  	  	     	W();
	  	  	  	  	     	W();
	  	  	  	  	     	A();
	  	  	  	  	     	S();
	  	  	  	  	     	posy2--;
	  	  	  	  	     }
	  	  	  	  }
	  	  	  	else//ly<posy2
	  	  	  	  {
	  	  	  	  	D();
	  	  	  	  	S();
	  	  	  	  	A();
	  	  	  	  	posx2++;
	  	  	  	  	while(posx2<x)
	  	  	  	  	     {
	  	  	  	  	     	W();
	  	  	  	  	     	D();
	  	  	  	  	     	D();
	  	  	  	  	     	S();	  	  	  	  	     	
	  	  	  	  	        A();
	  	  	  	  	        posx2++;
	  	  	  	  	     }
	  	  	  	  	W();
	  	  	  	  	D();
	  	  	  	  	S();
	  	  	  	  	posy2--;
	  	  	  	  	while(posy2>y)
	  	  	  	  	     {
	  	  	  	  	     	D();
	  	  	  	  	     	W();
	  	  	  	  	     	W();
	  	  	  	  	     	A();
	  	  	  	  	     	S();
	  	  	  	  	     	posy2--;
	  	  	  	  	     }
	  	  	  	  }
	  	  	  }
	  	  	 else//lx>posx2,posx2<x
	  	  	  {
	  	  	  	if(posy2==y+1 && ly==y)
	  	  	  	  {
	  	  	  	  	S();
	  	  	  	  	for(int i=lx;i>posx2;i--)
	  	  	  	       {
	  	  	  	   	     A();
	  	  	  	       }
	  	  	  	    posx2++;
	  	  	  	    while(posx2<x)
	  	  	  	         {
	  	  	  	         	S();
	  	  	  	         	D();
	  	  	  	         	D();
	  	  	  	         	W();
	  	  	  	         	A();
	  	  	  	         	posx2++;
	  	  	  	         }
	  	  	  	    S();
	  	  	  	    D();
	  	  	  	    while(posy2>y)
	  	  	  	         {
	  	  	  	         	D();
	  	  	  	         	W();
	  	  	  	         	W();
	  	  	  	         	A();
	  	  	  	         	S();
	  	  	  	         	posy2--;
	  	  	  	         }
	  	  	  	  }
	  	  	  	else//lx>posx2,posy2>y+1 || ly>posy2
	  	  	  	  {
	  	  	  	  	for(int i=lx;i>posx2;i--)
	  	  	  	  	   {
	  	  	  	  	   	A();
	  	  	  	  	   }
	  	  	  	  	if(ly<posy2)
	  	  	  	  	  {
	  	  	  	  	  	D();
	  	  	  	  	  	S();
	  	  	  	  	  	A();
	  	  	  	  	  	posx2++;
	  	  	  	  	  	while(posx2<x)
	  	  	  	  	  	     {
	  	  	  	  	  	     	W();
	  	  	  	  	  	     	D();
	  	  	  	  	  	     	D();
								S();
								A();
								posx2++;		   	  	  	  	  	  	    
							 } 
						W();
						D();
						S();
						posy2--;
						while(posy2>y)
						     {
						     	D();
						     	W();
						     	W();
						     	A();
						     	S();
						     	posy2--;
						     }
	  	  	  	  	  }
	  	  	  	  	else
	  	  	  	  	  {
	  	  	  	  	  	D();
	  	  	  	  	  	W();
	  	  	  	  	  	A();
	  	  	  	  	  	posx2++;
	  	  	  	  	  	while(posx2<x)
	  	  	  	  	  	     {
	  	  	  	  	  	     	S();
	  	  	  	  	  	     	D();
	  	  	  	  	  	     	D();
	  	  	  	  	  	     	W();
	  	  	  	  	  	     	A();
	  	  	  	  	  	     	posx2++;
	  	  	  	  	  	     }
	  	  	  	  	  	S();
	  	  	  	  	  	D();
	  	  	  	  	  	while(posy2>y)
	  	  	  	  	  	     {
	  	  	  	  	  	     	D();
	  	  	  	  	  	     	W();
	  	  	  	  	  	     	W();
	  	  	  	  	  	     	A();
	  	  	  	  	  	     	S();
	  	  	  	  	  	     	posy2--;
	  	  	  	  	  	     }
	  	  	  	  	  }
	  	  	  	  	
	  	  	  	  }
	  	  	  	
	  	  	  }
	  	  }
	  	  else
	  	    {
	  	    	if(posx2==x+1)
	  	    	  {
	  	    	  	if(ly<posy2)
	  	    	  	  {
	  	    	  	  	for(int i=ly;i<posy2-1;i++)
	  	    	  	  	   {
	  	    	  	  	   	S();
	  	    	  	  	   }
	  	    	  	  }
	  	    	  	else
	  	    	  	  {
	  	    	  	  	if(ly>posy2)
	  	    	  	  	  {
	  	    	  	  	  	for(int i=ly;i>posy2+1;i--)
	  	    	  	  	  	   {
	  	    	  	  	  	   	W();
	  	    	  	  	  	   }
	  	    	  	  	  }
	  	    	  	  	else
	  	    	  	  	  {
	  	    	  	  	  	if(posy2==M-1)
	  	    	  	  	  	  {
	  	    	  	  	  	  	W();
	  	    	  	  	  	  }
	  	    	  	  	  	else
	  	    	  	  	  	  {
	  	    	  	  	  	  	S();
	  	    	  	  	  	  }
	  	    	  	  	  }
	  	    	  	  	if(lx<posx2)
	  	    	  	  	  {
	  	    	  	  	  	for(int i=lx;i<posx2;i++)
	  	    	  	  	  	   {
	  	    	  	  	  	   	D();
	  	    	  	  	  	   }
	  	    	  	  	  }
                        if(ly<posy2)
						  {
						  	S();
						  	posy2--;
						  	while(posy2>y)
						  	     {
						  	       A();
								   W();
								   W();
								   D();
								   S();
								   posy2--;	
						  	     }
						  	A();
						  	W();
						  	D();
						  	posx2--;
						  }
						else
						  {
						   while(posy2>y)
						        {
						        	A();
						        	W();
						        	W();
						        	D();
						        	S();
						        	posy2--;
						        }
						    A();
						    W();
						    D();
						    posx2--;
						  } 
	  	    	  	  }
	  	    	  }
	  	    }
	     }
	  }
	 for(int i=0;i<M;i++)
	       {
	   	    for(int j=0;j<N;j++)
	   	      {
	   	   		if(now[i][j]==begin[y][x])
	   	   	      {
	   	   	     	posy1=i;
	   	   	  	    posx1=j;
	   	   	  	    break;
	   	   	  	  }
	   	   	  }
	  	   }
	if(posy1==y && posx1==x+1)
	  {
	  	for(int i=lx;i<N-1;i++)
	  	   {
	  	   	D();
	  	   }
	  	for(int i=ly;i>y;i--)
	  	   {
	  	   	W();
	  	   }
	  	posy1++;
	  	A();
	  	S();
	  	A();
	  	S();
	  	D();
	  	D();
	  	W();
	  	posy1++;
	  	W();
	  	A();
	  	S();
	  	D();
	  	W();
	  	A();
	  	S();
	  }
	else
	  {
		if(posy1==y+1 && posx1==x+1 && ly==y && lx==x+1)
		  {
		  	A();
	  		S();
	  		A();
	  		S();
	  		D();
	  		D();
	  		W();
	  		posy1++;
	  		W();
	  		A();
	  		S();
	  		D();
	  		W();
	  		A();
	  		S();
		  }
	  }
	if(posy1==y+1)//posy1==y+1
	  {
	   if(posx1!=x)
	  	{
	  	if(ly==y+1)
	  	  {
	  		if(posx1==x+1)
	  		  {
	  		  	for(int i=lx;i<posx1;i++)
	  		  	   {
	  		  	   	D();
	  		  	   }
	  		  	posx1--;
	  		  }
	  		else//posx1<x,posy1==y+1
	  		{
	  		 if(lx>posx1)
	  	      {
	  	  	    for(int i=lx;i>posx1;i--)
	  	  	       {
	  	  	   		A();
	  	  	   	   }
	  	  	   	posx1++;
	  	  	   	while(posx1<x)
	  	  	   	     {
	  	  	   	     	S();
	  	  	   	     	D();
	  	  	   	     	D();
	  	  	   	     	W();
	  	  	   	     	A();
	  	  	   	     	posx1++;
	  	  	   	     }
	  	  	  }
	  		else
	  	  	 {
	  	  		for(int i=lx;i<posx1-1;i++)
	  	  	   	   {
	  	  	   		D();
	  	  	       }
	  	  	    while(posx1<x)
					 {
					 	S();
					 	D();
					 	D();
					 	W();
					 	A();
					 	posx1++;
					 }	  	  	    
	  	     }
	  	    }
	  	  }
	  	else
	  	  {
	  		if(posx1<x)
	  		  {
	  		  	if(ly<posy1)
	  		  	{
	  		  	S();
	  		  	for(int i=lx;i>posx1;i--)
	  		  	   {
	  		  	   	A();
	  		  	   }
	  		  	posx1++;
	  		  	while(posx1<x)
	  		  	     {
	  		  	     	S();
	  		  	     	D();
	  		  	     	D();
	  		  	     	W();
	  		  	     	A();
	  		  	     	posx1++;
	  		  	     }
	  		    }
	  		    else
	  		    {
	  		      if(ly>posy1)
	  		        {
	  		        	for(int i=ly;i>posy1+1;i--)
	  		        	   {
	  		        	   	W();
	  		        	   }
	  		        	if(lx<=posx1)
	  		        	  {
	  		        	  	for(int i=lx;i<posx1;i++)
	  		        	  	   {
	  		        	  	   	D();
	  		        	  	   }
	  		        	  }
	  		        	else
	  		        	  {
	  		        	  	for(int i=lx;i>posx1;i--)
	  		        	  	   {
	  		        	  	   	A();
	  		        	  	   }
	  		        	  }
	  		        	D();
	  		        	W();
	  		        	A();
	  		        	posx1++;
	  		        	while(posx1<x)
	  		        	     {
	  		        	     	S();
	  		        	     	D();
	  		        	     	D();
	  		        	     	W();
	  		        	     	A();
	  		        	     	posx1++;
	  		        	     }
	  		        }
	  		    }
	  		  }
	  		else//posx1==x+1
	  		  {
	  		  	if(posx1==x+1)
	  		  	  {
	  		  	  	if(ly>posy1)
	  		  	  	  {
	  		  	  	  	for(int i=ly;i>posy1+1;i--)
	  		  	  	  	   {
	  		  	  	  	   	W();
	  		  	  	  	   }
	  		  	  	  	if(lx<posx1)
	  		  	  	  	  {
	  		  	  	  	  	for(int i=lx;i<posx1;i++)
	  		  	  	  	  	   {
	  		  	  	  	  	   	D();
	  		  	  	  	  	   }
	  		  	  	  	  	A();
	  		  	  	  	  	W();
	  		  	  	  	  	D();
	  		  	  	  	  	posx1--;
	  		  	  	  	  }
	  		  	  	  }
	  		  	  }
	  		  }
	  	  }
	    }	    
      }
    else//posy1!=y+1
      {
      	if(posy1>y+1)//posy1>y+1
      	  {
      	  	if(posx1==x+1)
      	  	  {
      	  	  	if(ly!=posy1)
      	  	  	  {
      	  	  	  	if(ly<posy1)
      	  	  	  	  {
      	  	  	  	  	for(int i=ly;i<posy1-1;i++)
      	  	  	  	  	   {
      	  	  	  	  	   	S();
      	  	  	  	  	   }
      	  	  	  	  }
      	  	  	  	else//ly>posy1
      	  	  	  	  {
      	  	  	  	  	for(int i=ly;i>posy1+1;i--)
      	  	  	  	  	   {
      	  	  	  	  	   	W();
      	  	  	  	  	   }
      	  	  	  	  }
      	  	  	  	for(int i=lx;i<posx1;i++)
      	  	  	  	   {
      	  	  	  	   	D();
      	  	  	  	   }
      	  	  	  	if(ly<posy1)
      	  	  	  	  {
      	  	  	  	  	A();
      	  	  	  	  	S();
      	  	  	  	  	D();
      	  	  	  	  	posx1--;
      	  	  	  	  	W();
      	  	  	  	  	A();
      	  	  	  	  	S();
      	  	  	  	  	posy1--;
      	  	  	  	  	while(posy1>y+1)
      	  	  	  	  	     {
      	  	  	  	  	      	D();
      	  	  	  	  	      	W();
      	  	  	  	  	      	W();
      	  	  	  	  	      	A();
      	  	  	  	  	      	S();
      	  	  	  	  	      	posy1--;
      	  	  	  	  	     }
      	  	  	  	  }
      	  	  	  	else//ly>posy1,lx==posx1==x+1
      	  	  	  	  {
      	  	  	  	  	A();
      	  	  	  	  	W();
      	  	  	  	  	D();
      	  	  	  	  	posx1--;
      	  	  	  	  	W();
      	  	  	  	  	A();
      	  	  	  	  	S();
      	  	  	  	  	posy1--;
      	  	  	  	  	while(posy1>y+1)
      	  	  	  	  	     {
      	  	  	  	  	      	D();
      	  	  	  	  	      	W();
      	  	  	  	  	      	W();
      	  	  	  	  	      	A();
      	  	  	  	  	      	S();
      	  	  	  	  	      	posy1--;
      	  	  	  	  	     }
      	  	  	  	  }
      	  	  	  }
      	  	  	else//ly==posy1
      	  	  	  {
      	  	  	    for(int i=lx;i<posx1;i++)
						{
							D();
						}
					posx1--;
					W();
      	  	  	  	A();
      	  	  	  	S();
      	  	  	  	posy1--;
      	  	  	  	while(posy1>y+1)
      	  	  	  	  	{
      	  	  	  	  	    D();
      	  	  	  	  	    W();
      	  	  	  	  	    W();
      	  	  	  	  	    A();
      	  	  	  	  	    S();
      	  	  	  	  	    posy1--;
      	  	  	  	  	}						
      	  	  	  }
      	  	  }
      	  	else
			{
			 if(posx1<x)
      	  	  {
      	  	  	if(ly<posy1)
      	  	  	  {
      	  	  	  	for(int i=ly;i<posy1-1;i++)
      	  	  	  	   {
      	  	  	  	   	S();
      	  	  	  	   }
      	  	  	  }
      	  	  	else
      	  	  	  {
      	  	  	  	if(ly>posy1)
      	  	  	  	  {
      	  	  	  	  	for(int i=ly;i>posy1+1;i--)
      	  	  	  	      {
      	  	  	  	   	   W();
      	  	  	  	      }
      	  	  	  	  }
      	  	  	  	else
      	  	  	  	  {
      	  	  	  	  	if(ly==M-1)
      	  	  	  	  	  {
      	  	  	  	  	  	W();
      	  	  	  	  	  }
      	  	  	  	  	else
      	  	  	  	  	  {
      	  	  	  	  	  	S();
      	  	  	  	  	  }
      	  	  	  	  }
      	  	  	  }
      	  	  	if(lx<=posx1)
      	  	  	  {
      	  	  	  	for(int i=lx;i<posx1;i++)
      	  	  	  	   {
      	  	  	  	   	D();
      	  	  	  	   }
      	  	  	  }
      	  	  	else
      	  	  	  {
      	  	  	  	for(int i=lx;i>posx1;i--)
      	  	  	  	   {
      	  	  	  	   	A();
      	  	  	  	   }
      	  	  	  }
      	  	  	if(ly<posy1)
      	  	  	  {
      	  	  	  	D();
      	  	  	  	S();
      	  	  	  	A();
      	  	  	  	posx1++;
      	  	  	  	while(posx1<x)
      	  	  	  	     {
      	  	  	  	     	W();
      	  	  	  	     	D();
      	  	  	  	     	D();
      	  	  	  	     	S();
      	  	  	  	     	A();
      	  	  	  	     	posx1++;
      	  	  	  	     }
      	  	  	  	W();
      	  	  	  	D();
      	  	  	  	S();
      	  	  	  	posy1--;
      	  	  	  	while(posy1>y+1)
      	  	  	  	     {
      	  	  	  	     	D();
      	  	  	  	     	W();
      	  	  	  	     	W();
      	  	  	  	     	A();
      	  	  	  	     	S();
      	  	  	  	     	posy1--;
      	  	  	  	     }
      	  	  	  }
      	  	  	else//ly>posy1
      	  	  	  {
      	  	  	  	D();
      	  	  	  	W();
      	  	  	  	A();
      	  	  	  	posx1++;
      	  	  	  	while(posx1<x)
      	  	  	  	     {
      	  	  	  	     	S();
      	  	  	  	     	D();
      	  	  	  	     	D();
      	  	  	  	     	W();
      	  	  	  	     	A();
      	  	  	  	     	posx1++;
      	  	  	  	     }
      	  	  	  	S();
      	  	  	  	D();
      	  	  	  	while(posy1>y+1)
      	  	  	  	     {
      	  	  	  	     	D();
      	  	  	  	     	W();
      	  	  	  	     	W();
      	  	  	  	     	A();
      	  	  	  	     	S();
      	  	  	  	     	posy1--;
      	  	  	  	     }
      	  	  	  }
      	  	  }
      	     else//posx1==x
      	       {
      	       	if(posx1==x)
      	       	  {
      	       	  	if(ly<posy1)
      	       	  	  {
      	       	  	  	for(int i=ly;i<posy1-1;i++)
      	       	  	  	   {
      	       	  	  	   	S();
      	       	  	  	   }
      	       	  	    if(lx<=posx1)
      	       	  	      {
      	       	  	      	for(int i=lx;i<posx1;i++)
      	       	  	      	   {
      	       	  	      	   	D();
      	       	  	      	   }
      	       	  	      }
      	       	  	    else
      	       	  	      {
      	       	  	      	for(int i=lx;i>posx1;i--)
      	       	  	      	   {
      	       	  	      	   	A();
      	       	  	      	   }
      	       	  	      }
      	       	  	    S();
      	       	  	    posy1--;
      	       	  	    while(posy1>y+1)
      	       	  	         {
      	       	  	         	D();
      	       	  	         	W();
      	       	  	         	W();
      	       	  	         	A();
      	       	  	         	S();
      	       	  	         	posy1--;
      	       	  	         }
      	       	  	  }    	       	  	
      	       	  	else
      	  	  	    {
      	  	  	  	if(ly>posy1)
      	  	  	  	  {
      	  	  	  	  	for(int i=ly;i>posy1+1;i--)
      	  	  	  	      {
      	  	  	  	   	   W();
      	  	  	  	      }
      	  	  	  	    if(lx<=posx1)
      	       	  	      {
      	       	  	      	for(int i=lx;i<posx1;i++)
      	       	  	      	   {
      	       	  	      	   	D();
      	       	  	      	   }
      	       	  	      }
      	       	  	    else
      	       	  	      {
      	       	  	      	for(int i=lx;i>posx1;i--)
      	       	  	      	   {
      	       	  	      	   	A();
      	       	  	      	   }
      	       	  	      }
      	       	  	    while(posy1>y+1)
      	       	  	         {
      	       	  	         	D();
      	       	  	         	W();
      	       	  	         	W();
      	       	  	         	A();
      	       	  	         	S();
      	       	  	         	posy1--;
      	       	  	         }
      	  	  	  	  }
      	  	  	  	else//ly==posy1
      	  	  	  	  {
      	  	  	  	  	if(ly==M-1)
      	  	  	  	  	  {
      	  	  	  	  	  	W();
      	  	  	  	  	  }
      	  	  	  	  	else
      	  	  	  	  	  {
      	  	  	  	  	  	S();
      	  	  	  	  	  }
      	  	  	  	  	if(lx<=posx1)
      	       	  	      {
      	       	  	      	for(int i=lx;i<posx1;i++)
      	       	  	      	   {
      	       	  	      	   	D();
      	       	  	      	   }
      	       	  	      }
      	       	  	    else
      	       	  	      {
      	       	  	      	for(int i=lx;i>posx1;i--)
      	       	  	      	   {
      	       	  	      	   	A();
      	       	  	      	   }
      	       	  	      }
      	       	  	    if(ly<posy1)
      	       	  	      {
      	       	  	      	S();
      	       	  	      	posy1--;
      	       	  	      	while(posy1>y+1)
      	       	  	         {
      	       	  	         	D();
      	       	  	         	W();
      	       	  	         	W();
      	       	  	         	A();
      	       	  	         	S();
      	       	  	         	posy1--;
      	       	  	         }
      	       	  	      }
      	       	  	    else
      	       	  	      {
      	       	  	      	while(posy1>y+1)
      	       	  	         {
      	       	  	         	D();
      	       	  	         	W();
      	       	  	         	W();
      	       	  	         	A();
      	       	  	         	S();
      	       	  	         	posy1--;
      	       	  	         }
      	       	  	      }
      	       	  	    
      	  	  	  	  }
      	  	  	    }
      	  	  	    
      	       	  }
      	       }
			}
      	  }
      }
	if(ly!=M-1)
	  {
	  	S();
	  }
	for(int i=lx;i<N-1;i++)
	   {
	   	D();
	   }
	for(int i=ly;i>y;i--)
	   {
	   	W();
	   }
	A();
	posx2++;
	S();
	posy1--;
	return;
}
